export const TYPES_WORKSPACE= {
  TYPE_LIST_WORKSPACES:"TYPE_LIST_WORKSPACES",
  TYPE_LIST_WORKSPACES_USER:"TYPE_LIST_WORKSPACES_USER",
  TYPE_WORKSPACE_BY_ID:"TYPE_LIST_WORKSPACES_USER",
}

export const TYPES_BOARD= {
  TYPE_LIST_BOARDS_BY_WORKSPACE:"TYPE_LIST_BOARDS_BY_WORKSPACE",
  TYPE_LIST_BOARDS_BY_WORKSPACE_AND_USER:"TYPE_LIST_BOARDS_BY_WORKSPACE_AND_USER",
  TYPE_DETAIL_BOARD:"TYPE_DETAIL_BOARD",
}
