export const TYPES_WORKSPACE= {
  TYPE_LIST_WORKSPACES:"TYPE_LIST_WORKSPACES",
  TYPE_LIST_WORKSPACES_USER:"TYPE_LIST_WORKSPACES_USER",
  TYPE_WORKSPACE_BY_ID:"TYPE_LIST_WORKSPACES_USER",
}

export const TYPES_BOARD= {
  TYPE_LIST_BOARDS_BY_WORKSPACE:"TYPE_LIST_BOARDS_BY_WORKSPACE",
  TYPE_LIST_BOARDS_BY_WORKSPACE_AND_USER:"TYPE_LIST_BOARDS_BY_WORKSPACE_AND_USER",
  TYPE_DETAIL_BOARD:"TYPE_DETAIL_BOARD",
}

export const TYPES_FEATURE= {
  TYPE_DETAIL_FEATURE:"TYPE_DETAIL_FEATURE",
  TYPE_LIST_ATTACHMENTS:"TYPE_LIST_ATTACHMENTS"
}

export const TYPES_TASKS = {
  TYPE_LIST_TASKS:"TYPE_LIST_TASKS"
}

export const TYPES_TAGS = {
  TYPE_LIST_TAGS:"TYPE_LIST_TAGS"
}
